# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"3\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"9\n\x14\x43reateProductRequest\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"V\n\x0fProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x07product\x18\x03 \x01(\x0b\x32\x10.product.Product\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\x12UpdateStockRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x32\xe4\x01\n\x0eProductService\x12H\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12\x42\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12\x44\n\x0bUpdateStock\x12\x1b.product.UpdateStockRequest\x1a\x18.product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=26
  _globals['_PRODUCT']._serialized_end=77
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=79
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=136
  _globals['_PRODUCTRESPONSE']._serialized_start=138
  _globals['_PRODUCTRESPONSE']._serialized_end=224
  _globals['_GETPRODUCTREQUEST']._serialized_start=226
  _globals['_GETPRODUCTREQUEST']._serialized_end=257
  _globals['_UPDATESTOCKREQUEST']._serialized_start=259
  _globals['_UPDATESTOCKREQUEST']._serialized_end=310
  _globals['_PRODUCTSERVICE']._serialized_start=313
  _globals['_PRODUCTSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
